"""OpenAI implementation of the LLM client interface."""

from __future__ import annotations

import json
import logging
import time
from abc import ABC, abstractmethod
from typing import Any, Iterator

from openai import APICONNECTIONERROR, AuthenticationError, OpenAI, RateLimitError
from openai import Stream as OpenAIStream
from openai.types.chat import ChatCompletion, ChatCompletionChunk
from pydantic import BaseModel, ValidationError

from app.config import get_settings
from app.llm.client import (
    AuthenticationError as AppAuthenticationError,
    EmptyResponseError,
    InvalidResponseError,
    LLMError,
    NetworkError,
    RateLimitError as AppRateLimitError,
    StructuredValidationError,
    TimeoutError as AppTimeoutError,
)

logger = logging.getLogger(__name__)

# Retry configuration
MAX_RETRIES = 3
INITIAL_RETRY_DELAY = 1.0  # seconds
RETRY_BACKOFF_MULTIPLIER = 2.0


class BaseLLMClient(ABC):
    """Abstract base class for LLM provider clients.

    This interface defines the contract that all provider implementations
    must follow, enabling easy swapping between different LLM providers.
    """

    @abstractmethod
    def generate_text(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.7,
        max_tokens: int | None = None,
    ) -> str:
        """Generate text from the LLM.

        Args:
            system_prompt: System-level instructions for the LLM.
            user_prompt: User query or input for the LLM.
            temperature: Sampling temperature (0.0 to 2.0).
            max_tokens: Maximum tokens to generate.

        Returns:
            The generated text content as a string.
        """
        pass

    @abstractmethod
    def generate_json(
        self,
        system_prompt: str,
        user_prompt: str,
        response_model: type[BaseModel],
        temperature: float = 0.7,
    ) -> BaseModel:
        """Generate structured JSON output validated against a Pydantic model.

        Args:
            system_prompt: System-level instructions for the LLM.
            user_prompt: User query or input for the LLM.
            response_model: Pydantic model class for structured output validation.
            temperature: Sampling temperature (0.0 to 2.0).

        Returns:
            An instance of the response_model with validated data.
        """
        pass

    @abstractmethod
    def stream_text(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.7,
    ) -> Iterator[str]:
        """Stream text chunks from the LLM.

        Args:
            system_prompt: System-level instructions for the LLM.
            user_prompt: User query or input for the LLM.
            temperature: Sampling temperature (0.0 to 2.0).

        Yields:
            Incremental text chunks as they are generated by the LLM.
        """
        pass


class OpenAIClient(BaseLLMClient):
    """OpenAI implementation of the LLM client interface.

    This class manages communication with OpenAI's API using the official
    Python SDK v1.x. It implements retry logic with exponential backoff
    for transient errors and converts SDK exceptions into application
    exceptions.
    """

    DEFAULT_MODEL = "gpt-4o"
    DEFAULT_TIMEOUT = 60.0  # seconds
    DEFAULT_TEMPERATURE = 0.7

    def __init__(
        self,
        api_key: str | None = None,
        model: str | None = None,
        timeout: float | None = None,
    ) -> None:
        """Initialize the OpenAI client.

        Args:
            api_key: OpenAI API key. If None, loads from settings.
            model: Model name to use. If None, loads from settings or uses default.
            timeout: Request timeout in seconds. If None, uses default.
        """
        self._settings = get_settings()

        # Load configuration
        self._api_key = api_key or self._settings.openai_api_key
        if not self._api_key:
            raise ValueError("OpenAI API key is required.")

        self._model = model or self._get_model_from_settings()
        self._timeout = timeout if timeout is not None else self.DEFAULT_TIMEOUT

        # Initialize OpenAI client once
        self._client = OpenAI(api_key=self._api_key, timeout=self._timeout)

    def _get_model_from_settings(self) -> str:
        """Get model name from environment settings or use default."""
        import os

        model_from_env = os.getenv("LLM_MODEL")
        if model_from_env:
            return model_from_env.strip()
        return self.DEFAULT_MODEL

    def generate_text(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = DEFAULT_TEMPERATURE,
        max_tokens: int | None = None,
    ) -> str:
        """Generate text from OpenAI with retry logic.

        Args:
            system_prompt: System-level instructions for the LLM.
            user_prompt: User query or input for the LLM.
            temperature: Sampling temperature (0.0 to 2.0).
            max_tokens: Maximum tokens to generate.

        Returns:
            The generated text content as a string.

        Raises:
            AppAuthenticationError: If API key is invalid.
            AppRateLimitError: If rate limit is exceeded.
            NetworkError: If network communication fails.
            AppTimeoutError: If request times out.
            EmptyResponseError: If LLM returns empty content.
            InvalidResponseError: If response is malformed.
            LLMError: For other LLM-related errors.
        """
        messages = self._build_messages(system_prompt, user_prompt)

        def _call() -> str:
            response = self._call_chat_completion(
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
            )
            return self._validate_text_response(response)

        return self._retry_with_backoff(_call)

    def generate_json(
        self,
        system_prompt: str,
        user_prompt: str,
        response_model: type[BaseModel],
        temperature: float = DEFAULT_TEMPERATURE,
    ) -> BaseModel:
        """Generate structured JSON output with retry logic.

        Args:
            system_prompt: System-level instructions for the LLM.
            user_prompt: User query or input for the LLM.
            response_model: Pydantic model class for structured output validation.
            temperature: Sampling temperature (0.0 to 2.0).

        Returns:
            An instance of the response_model with validated data.

        Raises:
            AppAuthenticationError: If API key is invalid.
            AppRateLimitError: If rate limit is exceeded.
            NetworkError: If network communication fails.
            AppTimeoutError: If request times out.
            EmptyResponseError: If LLM returns empty content.
            InvalidResponseError: If response is malformed.
            StructuredValidationError: If output fails Pydantic validation.
            LLMError: For other LLM-related errors.
        """
        messages = self._build_messages(system_prompt, user_prompt)

        def _call() -> BaseModel:
            response = self._call_structured_completion(
                messages=messages,
                response_model=response_model,
                temperature=temperature,
            )
            return self._validate_structured_response(response, response_model)

        return self._retry_with_backoff(_call)

    def stream_text(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = DEFAULT_TEMPERATURE,
    ) -> Iterator[str]:
        """Stream text chunks from OpenAI with retry logic.

        Args:
            system_prompt: System-level instructions for the LLM.
            user_prompt: User query or input for the LLM.
            temperature: Sampling temperature (0.0 to 2.0).

        Yields:
            Incremental text chunks as they are generated by the LLM.

        Raises:
            AppAuthenticationError: If API key is invalid.
            AppRateLimitError: If rate limit is exceeded.
            NetworkError: If network communication fails.
            AppTimeoutError: If request times out.
            LLMError: For other LLM-related errors.
        """
        messages = self._build_messages(system_prompt, user_prompt)

        def _call() -> OpenAIStream[ChatCompletionChunk]:
            return self._call_chat_completion_stream(
                messages=messages,
                temperature=temperature,
            )

        stream = self._retry_with_backoff(_call)

        for chunk in stream:
            content = self._extract_stream_content(chunk)
            if content:
                yield content

    def _build_messages(
        self, system_prompt: str, user_prompt: str
    ) -> list[dict[str, str]]:
        """Construct chat messages for the OpenAI API.

        Args:
            system_prompt: System-level instructions.
            user_prompt: User query or input.

        Returns:
            List of message dictionaries in the format expected by the API.
        """
        return [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]

    def _call_chat_completion(
        self,
        messages: list[dict[str, str]],
        temperature: float,
        max_tokens: int | None,
    ) -> ChatCompletion:
        """Call the OpenAI chat completion API for non-streaming text generation.

        Args:
            messages: List of chat messages.
            temperature: Sampling temperature.
            max_tokens: Maximum tokens to generate.

        Returns:
            ChatCompletion response from the API.

        Raises:
            Propagates OpenAI SDK exceptions for handling by _convert_exception.
        """
        kwargs: dict[str, Any] = {
            "model": self._model,
            "messages": messages,
            "temperature": temperature,
        }

        if max_tokens is not None:
            kwargs["max_tokens"] = max_tokens

        return self._client.chat.completions.create(**kwargs)

    def _call_structured_completion(
        self,
        messages: list[dict[str, str]],
        response_model: type[BaseModel],
        temperature: float,
    ) -> ChatCompletion:
        """Call the OpenAI chat completion API with structured output.

        Args:
            messages: List of chat messages.
            response_model: Pydantic model for structured output.
            temperature: Sampling temperature.

        Returns:
            ChatCompletion response from the API.

        Raises:
            Propagates OpenAI SDK exceptions for handling by _convert_exception.
        """
        json_schema = response_model.model_json_schema()

        return self._client.chat.completions.create(
            model=self._model,
            messages=messages,
            temperature=temperature,
            response_format={
                "type": "json_schema",
                "json_schema": {
                    "name": response_model.__name__,
                    "strict": True,
                    "schema": json_schema,
                },
            },
        )

    def _call_chat_completion_stream(
        self,
        messages: list[dict[str, str]],
        temperature: float,
    ) -> OpenAIStream[ChatCompletionChunk]:
        """Call the OpenAI chat completion API for streaming text generation.

        Args:
            messages: List of chat messages.
            temperature: Sampling temperature.

        Returns:
            Stream of ChatCompletionChunk objects.

        Raises:
            Propagates OpenAI SDK exceptions for handling by _convert_exception.
        """
        return self._client.chat.completions.create(
            model=self._model,
            messages=messages,
            temperature=temperature,
            stream=True,
        )

    def _validate_text_response(self, response: ChatCompletion) -> str:
        """Extract and validate text content from a chat completion response.

        Args:
            response: ChatCompletion response from the API.

        Returns:
            The validated text content.

        Raises:
            EmptyResponseError: If content is empty or missing.
            InvalidResponseError: If response structure is unexpected.
        """
        try:
            content = response.choices[0].message.content
            if content is None or content.strip() == "":
                raise EmptyResponseError("LLM returned empty content.")
            return content
        except (IndexError, AttributeError) as exc:
            raise InvalidResponseError(
                f"Unexpected response structure from LLM: {exc}"
            ) from exc

    def _validate_structured_response(
        self, response: ChatCompletion, response_model: type[BaseModel]
    ) -> BaseModel:
        """Validate structured response against Pydantic model.

        Args:
            response: ChatCompletion response from the API.
            response_model: Pydantic model class for validation.

        Returns:
            Validated instance of the response_model.

        Raises:
            EmptyResponseError: If content is empty or missing.
            InvalidResponseError: If response structure is unexpected.
            StructuredValidationError: If validation fails.
        """
        try:
            content = response.choices[0].message.content
            if content is None or content.strip() == "":
                raise EmptyResponseError("LLM returned empty structured content.")

            try:
                parsed_content = json.loads(content)
            except json.JSONDecodeError as exc:
                raise InvalidResponseError(
                    f"LLM returned invalid JSON: {exc}"
                ) from exc

            try:
                return response_model.model_validate(parsed_content)
            except ValidationError as exc:
                raise StructuredValidationError(
                    f"Failed to validate structured output: {exc}"
                ) from exc

        except (IndexError, AttributeError) as exc:
            raise InvalidResponseError(
                f"Unexpected structured response structure from LLM: {exc}"
            ) from exc

    def _extract_stream_content(self, chunk: ChatCompletionChunk) -> str:
        """Extract text content from a streaming chunk.

        Args:
            chunk: Single chunk from the streaming response.

        Returns:
            Text content from the chunk, or empty string if no content.
        """
        try:
            delta = chunk.choices[0].delta
            return delta.content or ""
        except (IndexError, AttributeError):
            return ""

    def _retry_with_backoff[T](self, func: callable[[], T]) -> T:
        """Execute a function with exponential backoff retry logic.

        Args:
            func: Function to execute. Should return a value or raise an exception.

        Returns:
            The return value of the function.

        Raises:
            AppAuthenticationError: For authentication failures (no retry).
            AppRateLimitError: For rate limit errors (retries with backoff).
            NetworkError: For network errors (retries with backoff).
            AppTimeoutError: For timeout errors (retries with backoff).
            LLMError: For other errors after retries exhausted.
        """
        last_exception: Exception | None = None
        delay = INITIAL_RETRY_DELAY

        for attempt in range(MAX_RETRIES + 1):
            try:
                return func()
            except AuthenticationError as exc:
                # Authentication errors should not be retried
                raise AppAuthenticationError(
                    "OpenAI authentication failed. Please check your API key."
                ) from exc
            except RateLimitError as exc:
                last_exception = exc
                if attempt < MAX_RETRIES:
                    logger.warning(
                        f"Rate limit exceeded, retrying in {delay:.1f}s "
                        f"(attempt {attempt + 1}/{MAX_RETRIES})"
                    )
                    time.sleep(delay)
                    delay *= RETRY_BACKOFF_MULTIPLIER
                else:
                    raise AppRateLimitError(
                        "OpenAI rate limit exceeded after retries."
                    ) from exc
            except APICONNECTIONERROR as exc:
                last_exception = exc
                if attempt < MAX_RETRIES:
                    logger.warning(
                        f"Network error, retrying in {delay:.1f}s "
                        f"(attempt {attempt + 1}/{MAX_RETRIES})"
                    )
                    time.sleep(delay)
                    delay *= RETRY_BACKOFF_MULTIPLIER
                else:
                    raise NetworkError(
                        "Failed to connect to OpenAI after retries."
                    ) from exc
            except Exception as exc:
                # Check for timeout-related errors
                if "timeout" in str(exc).lower():
                    last_exception = exc
                    if attempt < MAX_RETRIES:
                        logger.warning(
                            f"Timeout error, retrying in {delay:.1f}s "
                            f"(attempt {attempt + 1}/{MAX_RETRIES})"
                        )
                        time.sleep(delay)
                        delay *= RETRY_BACKOFF_MULTIPLIER
                    else:
                        raise AppTimeoutError(
                            "OpenAI request timed out after retries."
                        ) from exc
                else:
                    # Other exceptions are not retried
                    raise self._convert_exception(exc)

        # This should not be reached, but handle it for type safety
        if last_exception:
            raise self._convert_exception(last_exception)
        raise LLMError("Unexpected error in retry logic.")

    def _convert_exception(self, exc: Exception) -> Exception:
        """Convert OpenAI SDK exceptions into application exceptions.

        Args:
            exc: Original exception from the OpenAI SDK.

        Returns:
            Converted application exception.

        Raises:
            AppAuthenticationError: For authentication failures.
            AppRateLimitError: For rate limit errors.
            NetworkError: For network-related errors.
            AppTimeoutError: For timeout errors.
            LLMError: For other errors.
        """
        if isinstance(exc, AuthenticationError):
            return AppAuthenticationError(
                "OpenAI authentication failed. Please check your API key."
            )

        if isinstance(exc, RateLimitError):
            return AppRateLimitError(
                "OpenAI rate limit exceeded. Please try again later."
            )

        if isinstance(exc, APICONNECTIONERROR):
            return NetworkError(
                "Failed to connect to OpenAI. Please check your network connection."
            )

        if "timeout" in str(exc).lower():
            return AppTimeoutError(
                "OpenAI request timed out. Please try again."
            )

        logger.error(f"Unexpected OpenAI API error: {exc}", exc_info=True)
        return LLMError(
            f"An error occurred while communicating with OpenAI: {exc}"
        )

    @property
    def model(self) -> str:
        """Return the configured model name."""
        return self._model

    @property
    def timeout(self) -> float:
        """Return the configured timeout in seconds."""
        return self._timeout
